### PR TITLE
v1.8.0 - Pollen Pandeonium Update

### PR DESCRIPTION
**Pull request by HIDEN64**

### CODE REVIEW

**Comment by HIDEN64** [comment]
why the hell are all of my previous commits just gone :wat:

**Comment by HIDEN64** [comment]
oh i force pushed it wrong

**Comment by HIDEN64** [comment]
wait wtf i chose mine as the base

**Comment by floppydisk05** [comment]
what in the fuck

**Comment by HIDEN64** [comment]
github moment
i chose hbot as the base, not this :wat:

**Comment by floppydisk05** [comment]
"[HIDEN64](https://github.com/HIDEN64) wants to merge 91 commits into [nickandfloppy:master](https://github.com/nickandfloppy/NetRunner) from [HIDEN64:staging](https://github.com/HIDEN64/HBot/tree/staging)" is truly one of the best things I've ever seen

**Comment by HIDEN64** [comment]
blame github being dumb :kek:

**Pull request closed without merging**
