### PR TITLE
Change spaces to tabs in editor config to match existing indentation 

### PR DESCRIPTION
**Pull request by dkay0670**
Changes the editor config from spaces to tabs.
I assume you added this to keep the files consistent, but the current config will do the opposite. All of NetRunner is already tabs, so making the editor config spaces will cause more inconsistencies.

### CODE REVIEW

**Comment by floppydisk05** [comment]
Incorrect, the majority is actually spaces except a bunch of random parts that are tabs for some reason that I'm in the middle of fixing.

For example, BedCommand.cs
image

**Comment by dkay0670** [comment]
Well, I will fix that then

**Comment by dkay0670** [comment]
why tf are there merge conflicts

**Comment by floppydisk05** [comment]
Because you apparently don't know how to read.

**Comment by dkay0670** [comment]
no you don't know how to git and force pushed

**Comment by floppydisk05** [comment]
The force push was amending a previous commit and irrelevant, you clearly didn't read the words "that I'm in the middle of fixing".

**Comment by floppydisk05** [comment]
Considering the indentation issue is already fixed I'm closing this PR.

**Pull request closed without merging**
