### PR TITLE
update my server info

### PR DESCRIPTION
**Pull request by HIDEN64**

### CODE REVIEW

**Comment by floppydisk05** [comment]
Idk about adding a whitelist field

**Comment by floppydisk05** [comment]
It's also not a "function"

**Review by floppydisk05 — COMMENTED** [review]
Not sure about adding the whitelist field. Only one server uses it and it adds another field onto the embed

**Comment by nick99nack** [comment]
I don't see an issue with having it, except that it would add another embed field and make it not look as nice. What if we removed the cracked accounts thing? The whitelist part seems more useful than that.

**Comment by floppydisk05** [comment]
ig

**Comment by floppydisk05** [comment]
still tho

**Comment by floppydisk05** [comment]
also you're supposed to review it

**Comment by HIDEN64** [comment]
Updated it.

**Review by floppydisk05 — APPROVED** [review]
LGTM

**Pull request merged**
