### PR TITLE
A whole laundry list of stuff

### PR DESCRIPTION
**Pull request by HIDEN64**
- Switch resource validation to NetRunner's own repo to avoid weird stuff
- Change PlatformTarget to AnyCPU to avoid bullcrap with macOS/Linux
- Add 0 as a valid code to http because it does have a page on http.cat
- Change the term "error" in the aforementioned command to "HTTP Status code" because not all codes are errors
- Change the embed title of insult 
- Change the embed color of insult to gold, to be consistent with most other commands
- Change the git repository link in about to link to the GitHub repo 
- Bump the version number to 4.1.0 because why not

### CODE REVIEW

**Comment by HIDEN64** [comment]
Oh and don't mind the git bullshit in the commits. The way floppy merged my last PR was weird so it resulted in this.

**Review by floppydisk05 — APPROVED** [review]

**Comment by floppydisk05** [comment]
May I also say that the mcinfo command was moved to the config but then nick removed it

**Comment by nick99nack** [comment]
> May I also say that the mcinfo command was moved to the config but then nick removed it

What does that have to do with this PR

**Comment by floppydisk05** [comment]
> > May I also say that the mcinfo command was moved to the config but then nick removed it
> 
> What does that have to do with this PR

Read the file changes (McInfoCommand.cs, line 27)

**Pull request merged**
