### PR TITLE
Fix #10

### LINKED ISSUE #10: Badges & hierarchy position broken
`whois` displays "None" for badges regardless of whether the user has any badges or not.

Also something about the "hierarchy position" being fucked up idk

(Issue on behalf of @dkay0670 because he's busy or something)

### PR DESCRIPTION
**Pull request by dkay0670**
Fix #10
that stuff is dumb anyway

Signed-off-by: dkay0670 <63021402+dkay0670@users.noreply.github.com>

### CODE REVIEW

**Comment by floppydisk05** [comment]
What part of "I'll fix it tomorrow" do you not understand

**Comment by dkay0670** [comment]
I already fixed it

**Comment by floppydisk05** [comment]
No, you deleted it

**Comment by floppydisk05** [comment]
It's not making anything actually crash, I'll fix it when I have time

**Comment by dkay0670** [comment]
yeah it's useless

**Comment by floppydisk05** [comment]
didn't ask

**Comment by floppydisk05** [comment]
As previously stated, I will fix it when I have time, but it's not a major issue atm

**Comment by nick99nack** [comment]
Yeah it's dumb, we should just remove it

**Pull request closed without merging**
